[package]
name = "tetris"
version = "0.1.0"
edition = "2024"

[dependencies]
enumset = "1.1.10"
serde = "1.0.228"
serde_json = "1.0.149"
strum = { version = "0.27.2", features = ["derive"] }

[dev-dependencies]
criterion = "0.7"

[[bench]]
name = "movegen"
harness = false
